plugins:
  "@muskrat/swagger-routing-controllers":
    format: json
    swagger:
      swagger: "2.0"
      basePath: "/v1"
      host: "localhost"
      schemes:
      - "https"
      - "http"
      info:
        description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
        version: "1.0.0"
        title: "Swagger Petstore"
        termsOfService: "http://swagger.io/terms/"
        contact:
          email: "apiteam@swagger.io"
        license:
          name: "Apache 2.0"
          url: "http://www.apache.org/licenses/LICENSE-2.0.html"
      securityDefinitions:
        petstore_auth:
          type: "oauth2"
          authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
          flow: "implicit"
          scopes:
            write:pets: "modify pets in your account"
            read:pets: "read your pets"
        api_key:
          type: "apiKey"
          name: "api_key"
          in: "header"
      definitions:
classDecorators:
  - Controller
  - JsonController
